services:
  api:
    build:
      context: ./
    environment:
      NODE_ENV: production
      MAILTRAP_SECRET: $MAILTRAP_SECRET
      JWT_SECRET: $JWT_SECRET
      MONGODB_URI: $MONGODB_URI
    command: ["node", "server.js"]
    restart: always

    networks:
      - docker-bridge-1

    labels:
      - "traefik.enable=true"
      
      # HTTP Router
      - "traefik.http.routers.api-growthspring-http.rule=Host(`api.growthspringers.com`)"
      - "traefik.http.routers.api-growthspring-http.entrypoints=web"
      - "traefik.http.routers.api-growthspring-http.middlewares=to-https"

      # Middleware
      - "traefik.http.middlewares.to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.to-https.redirectscheme.permanent=true"

      # HTTPS Router
      - "traefik.http.routers.api-growthspring-https.rule=Host(`api.growthspringers.com`)"
      - "traefik.http.routers.api-growthspring-https.entrypoints=websecure"
      - "traefik.http.routers.api-growthspring-https.tls=true"
      - "traefik.http.services.api-growthspring-service.loadbalancer.server.port=80"
      - "traefik.http.routers.api-growthspring-https.tls.certresolver=myresolver"

  cron:
    build:
      context: ./
    environment:
      NODE_ENV: production
      MAILTRAP_SECRET: $MAILTRAP_SECRET
      JWT_SECRET: $JWT_SECRET
      MONGODB_URI: $MONGODB_URI
    command: ["node", "cron.js"]
    restart: always

networks:
  docker-bridge-1:
    external: true
