name: Run Tests

on:
  push:
    branches:
      - v2
  pull_request:
    branches:
      - v2
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
      - run: npm install
      - run: npm test
