name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - v2
      - main
  push:
    branches:
      - main   # keep push trigger only for deploy, not tests

jobs:
  tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'   # ensure tests only run on PR

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 18.205.163.202
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/apps/api-growthspring
            pm2 restart prod-api-growthspring
